"""Local Supervisor password verification, login throttling, and signed sessions."""

import asyncio
import functools
import hashlib
import hmac
import math
import re
import secrets
import threading
import time
import unicodedata
from collections.abc import Callable, Mapping
from contextlib import suppress
from dataclasses import dataclass
from pathlib import Path

MIN_PASSWORD_CHARS = 15
MAX_PASSWORD_CHARS = 4 * 1024
RECORD_STATE_CONFIGURED = "configured"
RECORD_STATE_ENROLLMENT_REQUIRED = "enrollment-required"
RECORD_STATE_RECOVERY_REQUIRED = "recovery-required"
RECORD_STATE_UNINITIALIZED = "uninitialized"

_SCHEME = "scrypt-v1"
_N, _R, _P, _DKLEN = 2**14, 8, 5, 32
_MAXMEM = 128 * _N * _R * 4  # scrypt uses about 16 MiB; retain explicit OpenSSL headroom.
_PARAMETERS = "ln=14,r=8,p=5,dk=32"
_VERIFIER = re.compile(rf"^{_SCHEME}\${re.escape(_PARAMETERS)}\$([0-9a-f]{{64}})\$([0-9a-f]{{64}})$")
# The common-password blocklist, generated by `blocklist/generate.py` from a pinned public corpus in comparison form.
BLOCKLIST_PATH = Path(__file__).resolve().parent / "blocklist" / "passwords.txt"
# Words the Supervisor's own context makes guessable; a password must keep 15 characters without them.
CONTEXT_WORDS = ("shimpz", "supervisor", "admin")

LOGIN_FAILURE_LIMIT = 5
LOGIN_LOCK_SECONDS = 60

# A session lasts at most a day from its sign-in and ends after an hour without Supervisor activity (NIST SP 800-63B-4
# AAL2). Activity is tracked only in this process, so a restart or an evicted session asks for a new sign-in.
TTL = 24 * 3600
IDLE_SECONDS = 3600
MAX_TRACKED_SESSIONS = 64
_SESSION_SCHEME = "v3"
_SESSION_SIGNATURE = re.compile(r"[0-9a-f]{64}\Z")
_SESSION_METHODS = frozenset({"totp", "webauthn"})


class PasswordRecordError(RuntimeError):
    """The stored Local Supervisor password record is not the exact current contract."""


class LoginRateLimitedError(RuntimeError):
    """A Local login cannot reserve one bounded password-verification attempt."""

    def __init__(self, retry_after: int) -> None:
        super().__init__("too many login attempts")
        self.retry_after = retry_after


@dataclass(frozen=True, slots=True)
class SessionEvidence:
    """Signed Local session evidence for one completed MFA ceremony."""

    issued_at: int
    method: str

    @property
    def expires_at(self) -> int:
        return self.issued_at + TTL


class SessionActivity:
    """The last Supervisor activity of each session this process issued, keyed by the token's digest.

    A session it never issued or no longer tracks is unknown and refused. Only activity moves `last_seen`, so a page
    polling in the background cannot keep an unattended session alive.
    """

    def __init__(
        self,
        *,
        clock: Callable[[], float] = time.monotonic,
        idle_seconds: int = IDLE_SECONDS,
        capacity: int = MAX_TRACKED_SESSIONS,
    ) -> None:
        self._clock = clock
        self._idle_seconds = idle_seconds
        self._capacity = capacity
        self._lock = threading.Lock()
        self._last_seen: dict[str, float] = {}

    @staticmethod
    def _key(token: str) -> str:
        return hashlib.sha256(token.encode("ascii")).hexdigest()

    def register(self, token: str) -> None:
        with self._lock:
            now = self._clock()
            for key in [key for key, seen in self._last_seen.items() if now - seen >= self._idle_seconds]:
                del self._last_seen[key]
            while len(self._last_seen) >= self._capacity:
                del self._last_seen[min(self._last_seen, key=self._last_seen.__getitem__)]
            self._last_seen[self._key(token)] = now

    def current(self, token: str, *, activity: bool) -> bool:
        """Whether the session is tracked and not idle; Supervisor activity also restarts its idle time."""
        key = self._key(token)
        with self._lock:
            now = self._clock()
            seen = self._last_seen.get(key)
            if seen is None:
                return False
            if now - seen >= self._idle_seconds:
                del self._last_seen[key]
                return False
            if activity:
                self._last_seen[key] = now
            return True


SESSIONS = SessionActivity()


class LocalLoginLimiter:
    """Bound the singleton Local login before any expensive password work begins."""

    def __init__(
        self,
        *,
        clock: Callable[[], float] = time.monotonic,
        failure_limit: int = LOGIN_FAILURE_LIMIT,
        lock_seconds: int = LOGIN_LOCK_SECONDS,
    ) -> None:
        self._clock = clock
        self._failure_limit = failure_limit
        self._lock_seconds = lock_seconds
        self._lock = threading.Lock()
        self._in_flight = False
        self._failures = 0
        self._locked_until = 0.0

    def begin(self) -> None:
        """Reserve the only hash slot or reject immediately without queueing."""
        with self._lock:
            now = self._clock()
            if self._locked_until > now:
                raise LoginRateLimitedError(max(1, math.ceil(self._locked_until - now)))
            if self._locked_until:
                self._failures = 0
                self._locked_until = 0.0
            if self._in_flight:
                raise LoginRateLimitedError(1)
            self._in_flight = True

    def finish(self, *, rejected: bool | None) -> int:
        """Release the hash slot and return a new lock duration, when one begins."""
        with self._lock:
            if not self._in_flight:
                raise RuntimeError("unbalanced Local login rate-limit permit")
            self._in_flight = False
            if rejected is None:
                return 0
            if not rejected:
                self._failures = 0
                self._locked_until = 0.0
                return 0
            self._failures += 1
            if self._failures < self._failure_limit:
                return 0
            self._locked_until = self._clock() + self._lock_seconds
            return self._lock_seconds


async def attempt_login(
    password: str,
    record: object,
    limiter: LocalLoginLimiter,
) -> tuple[bool, int]:
    """Reserve immediately and retain the slot until the off-loop derivation finishes."""
    limiter.begin()
    verified: bool | None = None
    worker = asyncio.create_task(asyncio.to_thread(verify_password, password, record))
    try:
        try:
            verified = await asyncio.shield(worker)
        except asyncio.CancelledError:
            with suppress(Exception):
                await worker
            raise
    finally:
        lock_seconds = limiter.finish(rejected=None if verified is None else not verified)
    return verified, lock_seconds


def new_secret() -> str:
    """Return one random 32-byte hex secret."""
    return secrets.token_hex(32)


def normalized_password(password: str) -> str:
    """Return the comparison form shared by the policy and the blocklist generator."""
    return " ".join(unicodedata.normalize("NFKC", password).casefold().split())


@functools.cache
def blocklist() -> frozenset[str]:
    """Load the bundled blocklist once; a missing or empty list fails closed."""
    entries = frozenset(BLOCKLIST_PATH.read_text(encoding="utf-8").splitlines())
    if not entries:
        raise RuntimeError("the Supervisor password blocklist is empty")
    return entries


def _is_repeated_unit(value: str) -> bool:
    return len(value) > 1 and value in (value + value)[1:-1]


def _without_context(normalized: str) -> str:
    remainder = normalized
    for word in CONTEXT_WORDS:
        remainder = remainder.replace(word, "")
    return " ".join(remainder.split())


def password_policy(password: str) -> str | None:
    """Return the exact policy rejection code for a new password, or ``None`` when it is admitted.

    A new password has at least 15 characters, is not in the common-password blocklist, is not one repeated unit, and
    keeps 15 characters of its own once the words its context makes guessable are removed (NIST SP 800-63B-4).
    """
    if len(password) < MIN_PASSWORD_CHARS:
        return "password-too-short"
    if len(password) > MAX_PASSWORD_CHARS:
        return "password-too-long"
    normalized = normalized_password(password)
    if len(normalized) < MIN_PASSWORD_CHARS:
        return "password-too-short"
    remainder = _without_context(normalized)
    if any(value in blocklist() or _is_repeated_unit(value) for value in (normalized, remainder)):
        return "password-blocklisted"
    if len(remainder) < MIN_PASSWORD_CHARS:
        return "password-blocklisted"
    return None


def _derive(password: str, salt: bytes) -> bytes:
    return hashlib.scrypt(
        password.encode("utf-8"),
        salt=salt,
        n=_N,
        r=_R,
        p=_P,
        dklen=_DKLEN,
        maxmem=_MAXMEM,
    )


def new_password_verifier(password: str) -> str:
    """Create one strict current-contract verifier for an admitted new password."""
    if violation := password_policy(password):
        raise ValueError(violation)
    salt = secrets.token_bytes(32)
    digest = _derive(password, salt)
    return f"{_SCHEME}${_PARAMETERS}${salt.hex()}${digest.hex()}"


def _password_material(record: object) -> tuple[bytes, bytes] | None:
    if not isinstance(record, Mapping):
        raise PasswordRecordError("Local Supervisor password record is invalid")
    verifier = record.get("password_verifier")
    if verifier is None:
        return None
    match = _VERIFIER.fullmatch(verifier) if isinstance(verifier, str) else None
    if match is None:
        raise PasswordRecordError("Local Supervisor password record requires bounded recovery")
    return bytes.fromhex(match.group(1)), bytes.fromhex(match.group(2))


def password_state(record: object) -> str:
    """Return whether the strict password verifier exists, independent of MFA enrollment."""
    if _password_material(record) is None:
        return RECORD_STATE_UNINITIALIZED
    return RECORD_STATE_CONFIGURED


def verify_password(password: str, record: object) -> bool:
    """Verify one bounded password against only the exact current record contract."""
    if not isinstance(password, str) or not 1 <= len(password) <= MAX_PASSWORD_CHARS:
        raise ValueError("invalid password input")
    material = _password_material(record)
    if material is None:
        raise PasswordRecordError("Local Supervisor password is not configured")
    salt, expected = material
    return hmac.compare_digest(_derive(password, salt), expected)


def issue_session(secret_hex: str, method: str, *, issued_at: int | None = None) -> str:
    """Mint and track one signed Local MFA session token, valid for `TTL` seconds from its sign-in."""
    if method not in _SESSION_METHODS:
        raise ValueError("invalid Local session authentication method")
    issued = int(time.time()) if issued_at is None else issued_at
    body = f"{_SESSION_SCHEME}:{issued}:{secrets.token_hex(8)}:pwd+{method}"
    sig = hmac.new(bytes.fromhex(secret_hex), body.encode("utf-8"), hashlib.sha256).hexdigest()
    token = f"{body}:{sig}"
    SESSIONS.register(token)
    return token


def _session_parts(token: str) -> tuple[list[str], str] | None:
    parts = token.split(":")
    # A cookie is attacker text that may decode to non-ASCII, which compare_digest raises on instead of refusing.
    if (
        len(parts) != 5
        or parts[0] != _SESSION_SCHEME
        or not parts[3].startswith("pwd+")
        or _SESSION_SIGNATURE.fullmatch(parts[4]) is None
    ):
        return None
    method = parts[3].removeprefix("pwd+")
    return (parts, method) if method in _SESSION_METHODS else None


def _signed_evidence(secret_hex: str, token: str) -> SessionEvidence | None:
    parsed = _session_parts(token) if secret_hex and token else None
    if parsed is None:
        return None
    parts, method = parsed
    body = ":".join(parts[:4])
    try:
        expected = hmac.new(bytes.fromhex(secret_hex), body.encode("utf-8"), hashlib.sha256).hexdigest()
    except ValueError:
        return None
    if not hmac.compare_digest(parts[4], expected) or not parts[1].isascii() or not parts[1].isdigit():
        return None
    return SessionEvidence(int(parts[1]), method)


def verify_session(secret_hex: str, token: str, *, activity: bool = False) -> SessionEvidence | None:
    """Return MFA evidence for an authentic, unexpired, tracked, and active Local session.

    `activity` marks the request as the Supervisor's own action, which restarts the session's idle time.
    """
    evidence = _signed_evidence(secret_hex, token)
    if evidence is None or not evidence.issued_at <= time.time() < evidence.expires_at:
        return None
    return evidence if SESSIONS.current(token, activity=activity) else None
